services:
  app:
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - pg14
    environment:
      RAILS_ENV: production
    command: bin/bundle exec puma --log-requests
  pg14:
    container_name: warm_heart_database
    image: postgres:14.5-alpine3.16
    command: postgres -p 5432 -c 'max_connections=200'
    env_file:
      - .env.production.local
    expose:
      - "5432"
    volumes:
      - /root/docker/docker-volumes/pg14-warm-hearts:/var/lib/postgresql14/data

networks:
  default:
    name: warm-hearts
    external: true