shared:
  recaptcha_site_key: 6LdPTB0pAAAAAD_xaweIc1H1a4QGqRp2WHL5_wRh
  recaptcha_secret_key: 6LdPTB0pAAAAAKxKVwoz_n-jf2uFlVZhHyK50kdC

production:
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
