shared:
  recaptcha_site_key: <%= ENV.fetch('RECAPTCHA_SITE_KEY') %>
  recaptcha_secret_key: <%= ENV.fetch('RECAPTCHA_SECRET_KEY') %>

production:
  recaptcha_site_key: <%= ENV.fetch('RECAPTCHA_SITE_KEY') %>
  recaptcha_secret_key: <%= ENV.fetch('RECAPTCHA_SECRET_KEY') %>
